Handling undefined/null data
mikeerickson/validatorjs pull request #157
Opened 2017-03-03 01:17 UTC by mgibas

Without this check Validator throws exception:
```
Cannot convert undefined or null to object at hasOwnProperty
```

2017-03-11 08:18 UTC, iamdtang requested changes

2017-03-11 08:18 UTC, skaterdav85 commented on spec/validator.js
> +    validator.check();
I think there should be an assertion here that verifies the validation has failed. What do you think @garygreen?

2017-03-11 08:18 UTC, skaterdav85 commented on spec/validator.js
> +    validator.check();
Same as above.

2017-03-11 08:18 UTC, skaterdav85 commented on spec/validator.js
> +    validator = new Validator(undefined, { name: 'required' })
missing var

2017-03-11 08:18 UTC, skaterdav85 commented on spec/validator.js
> +    validator = new Validator(null, { name: 'required' })
missing var

2017-03-11 08:18 UTC, skaterdav85 commented on spec/validator.js
> +  it('should handle null data', function(){
add a space before the  {

2017-03-13 23:21 UTC, mgibas commented on spec/validator.js
> +    validator.check();
fixed

2017-03-13 23:21 UTC, mgibas commented on spec/validator.js
> +    validator = new Validator(null, { name: 'required' })
fixed

2017-03-13 23:21 UTC, mgibas commented on spec/validator.js
> +  it('should handle null data', function(){
fixed

2017-03-13 23:21 UTC, mgibas commented on spec/validator.js
> +    validator = new Validator(undefined, { name: 'required' })
fixed

2017-03-14 08:51 UTC, iamdtang requested changes

2017-03-14 08:51 UTC, skaterdav85 commented on spec/validator.js
> +  })
add a semicolon please

2017-03-14 08:51 UTC, skaterdav85 commented on spec/validator.js
> +  })
add a semicolon please

2017-03-14 08:51 UTC, skaterdav85 commented on spec/validator.js
> +    validator.check();
I don't think check is part of the public API. How about using something like this: http://chaijs.com/api/bdd/#method_throw to verify that the validator doesn't throw when fails() is called?

2017-03-14 08:51 UTC, skaterdav85 commented on spec/validator.js
> +    validator.check();
same as previous comment about check()

2017-03-14 12:00 UTC, mgibas commented on spec/validator.js
> +  })
That made me think: why the heck my linter stoped working?! :)

2017-03-14 12:01 UTC, mgibas commented on spec/validator.js
> +    validator.check();
Yeah - thats much better

2017-03-15 01:19 UTC, mgibas commented on spec/validator.js
> +    validator.check();
There is some weird thing with this:
`expect(fn).to.throw(Error)`
its calling asserted method with wrong scope which screws up `this` inside validator instance and gives me this error:
`AssertionError: expected [Function: fails] to not throw 'Error' but 'TypeError: this._checkAsync is not a function' was thrown`.
I switched to a `fails()` method though.

2017-04-11 18:10 UTC, merged