158 get method not returning all items
mikeerickson/validatorjs pull request #161
Opened 2017-03-10 01:04 UTC by mikeerickson

- [ ] Fixed issue when using `validator.errors.all()` and `validator.errors.get('attr')` when defining multiple rules (such as `min:10|emal`)   This does not affect issue when `required` is supplied.
- [ ] Added new test to verify this condition
- [ ] Ran full test suite (`npm test`) to assure all builds and validates

Fixes https://github.com/skaterdav85/validatorjs/issues/158

2017-03-11 08:12 UTC, iamdtang requested changes

2017-03-11 08:12 UTC, skaterdav85 commented on spec/error-messages.js
> +      expect(validator.errors.get('email').length).to.equal(2);
duplicate assertion?

2017-03-11 17:05 UTC, iamdtang approved these changes
looks good to me. @garygreen ?

2017-03-16 19:32 UTC, mikeerickson commented
@garygreen hey bud, just checking in.  Did you have any further requests?

2017-03-16 22:08 UTC, garygreen commented
Looks good to me too

2017-03-16 22:23 UTC, merged