117 extend date validation with moment
mikeerickson/validatorjs pull request #163
Opened 2017-03-11 17:07 UTC by mikeerickson

- [x] Refactored `date` rule to perform additional test using `moment` if installed
- [x] Updated `spec/date-rule.js` to conditionally handle bad date testing
- [x] Ran full test suite to confirm passing and dist built

NOTE: `moment` lib is included for `dev` mode but listed as `peerDependency` for distribution purposes.   Moment is NOT REQUIRED to use Validator, but will validate more accurately when installed.

2017-03-11 17:18 UTC, iamdtang requested changes

2017-03-11 17:18 UTC, skaterdav85 commented on spec/date-rule.js
> +      if ((idx === 1) || (idx === 2) || (idx === 3)) {
I think if we're going to check against individual dates in `asserts`, we should get rid of the `forEach` and write out each of those assertions for clarity.

2017-03-11 17:18 UTC, skaterdav85 commented on src/rules.js
> +      if(e.code ==='MODULE_NOT_FOUND') {
Is the condition that checks for `e.code` necessary?

2017-03-11 19:36 UTC, mikeerickson commented on spec/date-rule.js
> +      if ((idx === 1) || (idx === 2) || (idx === 3)) {
@skaterdav85 works for me, i will make adjustment

2017-03-11 19:37 UTC, mikeerickson commented on src/rules.js
> +      if(e.code ==='MODULE_NOT_FOUND') {
@skaterdav85 I don't see any compelling reason for making the check... I will remove it.

2017-03-11 19:51 UTC, iamdtang requested changes

2017-03-11 19:51 UTC, skaterdav85 commented on spec/date-rule.js
> -    var asserts = [
I think we still want tests for each item in `asserts`

2017-03-11 20:01 UTC, mikeerickson commented on spec/date-rule.js
> -    var asserts = [
@skaterdav85 Would you prefer the it block to have 4 different assertions, or would you prefer for it blocks, with one assertion each?

2017-03-11 20:21 UTC, skaterdav85 commented on spec/date-rule.js
> -    var asserts = [
I'd say each one will be its own test with 1 assertion

2017-03-16 19:30 UTC, mikeerickson commented
@skaterdav85 hey David, I made the requested changes.  Perhaps you misssed it.

2017-03-16 22:27 UTC, skaterdav85 commented on src/rules.js
> +      moment = require('moment');
hey so will this work in the browser, or will it throw an error like "undefined (require) is not a function"?

2017-03-16 22:28 UTC, skaterdav85 commented
@mikeerickson hey added one more comment

2017-03-18 20:16 UTC, mikeerickson commented
@skaterdav85 Ya, you are indeed correct... It was passing here because my build had moment bundled into the UMD module (which it should not have).

So, I have spent the morning creating a separate validation routine, which I am going to suggest as a replacement for moment (if you dont mind)

2017-03-18 20:23 UTC, mikeerickson commented
Hey David

If you don’t mind, can you add me as user to repo so that I can assign myself to any issue that I could handle.   I will basically try and triage all tickets and fix them as they come up


Regards,

Mike Erickson

2017-03-18 20:23 UTC, skaterdav85 commented
@mikeerickson cool! are you basically going create a lighter weight moment for the specific cases for this library?

2017-03-18 20:24 UTC, mikeerickson commented
@skaterdav85 Yes, that is the plan :-)

2017-03-19 01:21 UTC, closed without merging